src/Entity/Member.php
<?php

namespace App\Entity;

use App\Repository\MemberRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: MemberRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Member implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255)]
    private ?string $civilite = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'id_member', targetEntity: Commande::class)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setIdMember($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getIdMember() === $this) {
                $commande->setIdMember(null);
            }
        }

        return $this;
    }
}

src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\Column(length: 255)]
    private ?string $modele = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column]
    private ?int $prix_journalier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'vehicule', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): self
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setVehicule($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getVehicule() === $this) {
                $commande->setVehicule(null);
            }
        }

        return $this;
    }
}

src/Controller/RentaCarController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class RentaCarController extends AbstractController
{
    #[Route('/renta/car', name: 'app_renta_car')]
    public function index(): Response
    {
        return $this->render('renta_car/index.html.twig', [
            'controller_name' => 'RentaCarController',
        ]);
    }


    #[Route("/", name:"home")]
    public function indexAction()
    {
 
        return $this->render('renta_car/index.html.twig');
    }

    #[Route("/liste", name:"liste")]
    public function listeAction()
    {
 
        return $this->render('renta_car/liste.html.twig');
    }
}

templates/renta_car/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RentaCarController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Welcome to RentaCar!</h1>


<div class="card border-primary mb-3" style="max-width: 37rem;">
  <div class="card-header">RentaCar</div>
  <div class="card-body">
 
    <h3 text center class="card-title">Select your Car</h3>
     <td><img src="https://s03.s3c.es/imag/_v0/770x420/6/5/a/490x_coches-fondo-blanco-dreamstime.jpg" style="width:550px;" alt="550px"></td>
    <h3 class="card-text">A wide range of vehicles at your disposal at an extraordinary price, compare it!</h3>
  </div>
</div>
 <ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" href="{{ path('liste') }}  ">Select your Car</a>
  </li>


{% endblock %}

templates/renta_car/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RentaCarController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Welcome to RentaCar!</h1>

  

<div class="card border-primary mb-3" style="max-width: 37rem;">
  <div class="card-header">RentaCar</div>
  <div class="card-body">
 
   
<h3 text center class="card-title">Mercedes-Benz</h3>
     <td><img src="https://memolira.com/wp-content/uploads/2022/02/Mercedes-AMG-Vision-Gran-Turismo-2.jpeg" style="width:550px;" alt="550px"></td>
    <h3 class="card-text">AMG Vision Grand tourisme</h3>
    <ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" href="">Commandez</a>
  </li>
  </div>
</div>

<div class="card border-primary mb-3" style="max-width: 37rem;">
  <div class="card-header">RentaCar</div>
  <div class="card-body">
 
    <h3 text center class="card-title">Hennessey Venom</h3>
     <td><img src="https://sf2.autoplus.fr/wp-content/uploads/autoplus/2020/12/la-hennessey-venom-2020-serie-prete-pour-record.jpeg" style="width:550px;" alt="550px"></td>
    <h3 class="card-text">
Hennessey Venom F5-2020</h3>
<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" href="  ">Commandez</a>
  </li>
  </div>
</div>

<div class="card border-primary mb-3" style="max-width: 37rem;">
  <div class="card-header">RentaCar</div>
  <div class="card-body">
 
    <h3 text center class="card-title">Aston Martin Valkyrie</h3>
     <td><img src="https://amsc-prod-cd.azureedge.net/-/media/aston-martin/images/default-source/models/valkyrie/new/valkyrie-right-gallery.jpg?mw=1920&rev=-1&hash=6A076D1DD9B6044F1F55ABF2BEAF24FD" style="width:550px;" alt="550px"></td>
    <h3 class="card-text"> AM-RB 001</h3>
    <ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" href="  ">Commandez</a>
  </li>
   
  </div>
</div>


{% endblock %}

templates/renta_car/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {% endblock %}

{% block body %}



<table class="table table-bordered text-center">
    <thead>
        <tr>
            {% for colonne in colonnes %}
                <th>{{ colonne }}</th>
            {% endfor %}
            <th>Editer</th>
            <th>Supprimer</th>
        </tr>
    </thead>
    <tbody>
    {% for vehicule in vehicules %}
        <tr>
            <td>{{ vehicule.id }}</td>
            <td>{{ vehicule.titre}}</td>
            <td>{{ vehicule.marque}}</td>
            <td>{{ vehicule.modele}}</td>
            <td>{{ vehicule.description}}</td>
            <td><img src="{{ vehicule.photo }}" style="width: 150px;" alt=""></td>
            <td>{{ vehicule.prixJournalier}}</td>
            <td>{{ vehicule.dateEnregistrement|date('d/m/Y à H:i:s') }}</td>
            <td><a href="{{ path('admin_edit_vehicule',{id: vehicule.id}) }}" class="text-dark"><i class="fas fa-edit"></i></a></td>
            <td><a onclick="return confirm('voulez-vous supprimer cet vehicule ?')" href="{{ path('admin_delete_vehicule',{id: vehicule.id}) }}" class="text-dark"><i class="fas fa-trash"></i></a></td> 
        </tr>
    {% endfor %}
        </tbody>
</table>

{% endblock %}